---
title: "The Impact of State-Affiliated Media Outlets on the Online Information Environment"
#author: "Saurabh Khanna"
date: "Updated: `r format(Sys.Date(), format='%B %d %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 5
---

---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.retina = 4)
```


```{r message=FALSE, warning=FALSE, fig.retina=4}
# Libraries
pacman::p_load(tidyverse, countrycode, sf, state, htmltools, htmlwidgets, janitor, RColorBrewer, ussf, arrow, hrbrthemes, lubridate, estimatr, texreg, readxl, corrr)

options(arrow.skip_nul = TRUE)
```



```{r}
# Load data

df_yandex <- read_parquet(here::here("data/shared/webconf2023/yandex/yandex_trends_page1.parquet"))

df_google <- 
  bind_rows(
    read_parquet(here::here("data/shared/webconf2023/russia.parquet")),
    read_parquet(here::here("data/shared/webconf2023/ukraine.parquet")), 
    read_parquet(here::here("data/shared/webconf2023/united_kingdom.parquet")),
    read_parquet(here::here("data/shared/webconf2023/united_states.parquet"))
  )
```


# Russian State Media

## Yandex Only

```{r}
df_yandex %>% 
  mutate(
    rsm_domain = str_detect(domain, "rt.com|ria.ru|tass.com|tass.ru|lenta.ru|sputnik|tvzvezda.ru|redfish.media|gazeta.ru|ruptly.tv"),
  ) %>%
  group_by(date_clean) %>% 
  summarize(
    prop_rsm = mean(rsm_domain, na.rm = T)
  ) %>% 
  filter(year(date_clean) > 2021) %>% 
  ggplot(aes(date_clean, prop_rsm)) +
  geom_smooth(method = "loess", se = T, span = 0.1) +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-02-24")), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-04-07")), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-09-05")), linetype = "dashed", color = "red") +
  scale_x_datetime(breaks = "1 month", labels = scales::date_format("%B")) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = -45), legend.position = "bottom") +
  labs(
    x = "", y = "% Russian State Media Results on First Results Page"
  )
```

## Yandex vs Google Web

```{r}
bind_rows(
  "Yandex Web Russia" = df_yandex,
  "Google Web Russia" = df_google %>% filter(country == "russia", rank_group <= 14, type == "organic"),
  "Google Web Ukraine" = df_google %>% filter(country == "ukraine", rank_group <= 14, type == "organic"),
  "Google Web US" = df_google %>% filter(country == "united_states", rank_group <= 14, type == "organic"),
  "Google Web UK" = df_google %>% filter(country == "united_kingdom", rank_group <= 14, type == "organic"),
  .id = "dataset"
) %>%
  mutate(
    rsm_domain = str_detect(domain, "rt.com|ria.ru|tass.com|tass.ru|lenta.ru|sputnik|tvzvezda.ru|redfish.media|gazeta.ru|ruptly.tv"),
  ) %>%
  group_by(date_clean, dataset) %>% 
  summarize(
    prop_rsm = mean(rsm_domain, na.rm = T)
  ) %>% 
  filter(year(date_clean) > 2021) %>% 
  ggplot(aes(date_clean, prop_rsm)) +
  geom_smooth(method = "loess", se = F, span = 0.1, aes(color = dataset)) +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-02-24")), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-04-07")), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-09-05")), linetype = "dashed", color = "red") +
  scale_x_datetime(breaks = "1 month", labels = scales::date_format("%B")) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = -45), legend.position = "bottom") +
  labs(
    x = "", y = "% Russian State Media Results on First Results Page", color = ""
  )
```

## Yandex vs Google News

```{r}
bind_rows(
  "Yandex Web Russia" = df_yandex,
  "Google News Russia" = df_google %>% filter(country == "russia", rank_group <= 14, type == "news_search"),
  "Google News Ukraine" = df_google %>% filter(country == "ukraine", rank_group <= 14, type == "news_search"),
  "Google News US" = df_google %>% filter(country == "united_states", rank_group <= 14, type == "news_search"),
  "Google News UK" = df_google %>% filter(country == "united_kingdom", rank_group <= 14, type == "news_search"),
  .id = "dataset"
) %>%
  mutate(
    rsm_domain = str_detect(domain, "rt.com|ria.ru|tass.com|tass.ru|lenta.ru|sputnik|tvzvezda.ru|redfish.media|gazeta.ru|ruptly.tv"),
  ) %>%
  group_by(date_clean, dataset) %>% 
  summarize(
    prop_rsm = mean(rsm_domain, na.rm = T)
  ) %>% 
  filter(year(date_clean) > 2021) %>% 
  ggplot(aes(date_clean, prop_rsm)) +
  geom_smooth(method = "loess", se = F, span = 0.1, aes(color = dataset)) +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-02-24")), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-04-07")), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.POSIXct(as.Date("2022-09-05")), linetype = "dashed", color = "red") +
  scale_x_datetime(breaks = "1 month", labels = scales::date_format("%B")) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = -45), legend.position = "bottom") +
  labs(
    x = "", y = "% Russian State Media Results on First Results Page", color = ""
  )
```


# Variation with Search Rank

## Google web search

```{r}
bind_rows(
  "Google Web Russia" = df_google %>% filter(country == "russia", rank_group <= 14, type == "organic"),
  "Google Web Ukraine" = df_google %>% filter(country == "ukraine", rank_group <= 14, type == "organic"),
  "Google Web US" = df_google %>% filter(country == "united_states", rank_group <= 14, type == "organic"),
  "Google Web UK" = df_google %>% filter(country == "united_kingdom", rank_group <= 14, type == "organic"),
  .id = "dataset"
) %>%
  mutate(
    rsm_domain = str_detect(domain, "rt.com|ria.ru|tass.com|tass.ru|lenta.ru|sputnik|tvzvezda.ru|redfish.media|gazeta.ru|ruptly.tv"),
  ) %>% 
  group_by(country, rsm_domain) %>% 
  summarize(mean_result_rank = mean(rank_group, na.rm = T)) %>% 
  ggplot(aes(country, mean_result_rank)) +
  geom_col(aes(fill = rsm_domain), position = "dodge", alpha = 0.85) +
  scale_y_continuous(breaks = scales::breaks_width(1)) +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal() +
  labs(
    x = "", y = "Mean Result Rank", fill = "RSM Domain"
  )
```


## Google news search

```{r}
bind_rows(
  "Google News Russia" = df_google %>% filter(country == "russia", rank_group <= 14, type == "news_search"),
  "Google News Ukraine" = df_google %>% filter(country == "ukraine", rank_group <= 14, type == "news_search"),
  "Google News US" = df_google %>% filter(country == "united_states", rank_group <= 14, type == "news_search"),
  "Google News UK" = df_google %>% filter(country == "united_kingdom", rank_group <= 14, type == "news_search"),
  .id = "dataset"
) %>%
  mutate(
    rsm_domain = str_detect(domain, "rt.com|ria.ru|tass.com|tass.ru|lenta.ru|sputnik|tvzvezda.ru|redfish.media|gazeta.ru|ruptly.tv"),
  ) %>% 
  group_by(country, rsm_domain) %>% 
  summarize(mean_result_rank = mean(rank_group, na.rm = T)) %>% 
  mutate(country = str_replace_all(country, "_", " ") %>% str_to_title()) %>% 
  ggplot(aes(country, mean_result_rank)) +
  geom_col(aes(fill = rsm_domain), position = "dodge", alpha = 0.85) +
  scale_y_continuous(breaks = scales::breaks_width(1)) +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal() +
  labs(
    x = "", y = "Mean Result Rank", fill = "RSM Domain"
  )
```


